! This file is automatically generated by parse_ham.py
! Please note that all manual changes will be overwritten during compilation!
! Supplies subroutine for automatically reading and writing the parameters of "Hubbard_Plain_Vanilla"

      Subroutine read_parameters()
         use iso_fortran_env, only: error_unit
#ifdef MPI
         Use mpi
#endif
         Implicit none

         !Local variables
         integer            :: ierr, unit_para
         Character (len=64) :: file_info, file_para
         Integer, parameter :: dp = kind(0.d0)

         NAMELIST /VAR_lattice/  Model, Lattice_type, L1, L2
         NAMELIST /VAR_Hubbard_Plain_Vanilla/  ham_T, ham_Ty, Ham_chem, &
              &     Ham_U, Dtau, Beta, Projector, Theta, Symm, N_part

#ifdef MPI
         Integer        :: Isize, Irank, igroup, irank_g, isize_g
         Integer        :: STATUS(MPI_STATUS_SIZE)
         CALL MPI_COMM_SIZE(MPI_COMM_WORLD,ISIZE,IERR)
         CALL MPI_COMM_RANK(MPI_COMM_WORLD,IRANK,IERR)
         call MPI_Comm_rank(Group_Comm, irank_g, ierr)
         call MPI_Comm_size(Group_Comm, isize_g, ierr)
         IF (ierr /= 0) THEN
            WRITE(error_unit,*) 'read_parameters: Error in MPI', ierr
            error stop 1
         END IF
         igroup           = irank/isize_g
#endif

         !Parameters VAR_lattice
         Model        = ""       ! Value irrelevant
         Lattice_type = "Square" ! Possible Values: 'Square'
         L1           = 6        ! Length in direction a_1
         L2           = 6        ! Length in direction a_2
         !Parameters VAR_Hubbard_Plain_Vanilla
         ham_T     = 1.0d0   ! Hopping parameter
         ham_Ty    = 1.0d0   ! Hopping parameter   !#? declared ty
         Ham_chem  = 0.0d0   ! Chemical potential
         Ham_U     = 4.0d0   ! Hubbard interaction
         Dtau      = 0.1d0   ! Thereby Ltrot=Beta/dtau
         Beta      = 5.0d0   ! Inverse temperature
         Projector = .false. ! Whether the projective algorithm is used
         Theta     = 10.0d0  ! Projection parameter
         Symm      = .true.  ! Whether symmetrization takes place
         N_part    = -1      ! Number of particles in trial wave function. 
                             ! If N_part < 0 -> N_part = L1*L2/2
#ifdef MPI
         If (Irank_g == 0 ) then
#endif
#ifdef TEMPERING
            write(file_para,'(A,I0,A)') "Temp_", igroup, "/parameters"
            write(file_info,'(A,I0,A)') "Temp_", igroup, "/info"
#else
            file_para = "parameters"
            file_info = "info"
#endif

            !Read in parameters
            OPEN(NEWUNIT=unit_para, FILE=file_para, STATUS='old', ACTION='read', IOSTAT=ierr)
            IF (ierr /= 0) THEN
               WRITE(error_unit,*) 'unable to open <parameters>', ierr
               error stop 1
            END IF
            REWIND(unit_para)
            READ(unit_para, NML=VAR_lattice)
            REWIND(unit_para)
            READ(unit_para, NML=VAR_Hubbard_Plain_Vanilla)
            close(unit_para)

#ifdef MPI
         Endif
         !Broadcast parameters to all MPI tasks
         CALL MPI_BCAST(Model       , 64,MPI_CHARACTER,0,Group_Comm,ierr)
         CALL MPI_BCAST(Lattice_type, 64,MPI_CHARACTER,0,Group_Comm,ierr)
         CALL MPI_BCAST(L1          ,  1,MPI_INTEGER  ,0,Group_Comm,ierr)
         CALL MPI_BCAST(L2          ,  1,MPI_INTEGER  ,0,Group_Comm,ierr)
         CALL MPI_BCAST(ham_T    ,  1,MPI_REAL8    ,0,Group_Comm,ierr)
         CALL MPI_BCAST(ham_Ty   ,  1,MPI_REAL8    ,0,Group_Comm,ierr)
         CALL MPI_BCAST(Ham_chem ,  1,MPI_REAL8    ,0,Group_Comm,ierr)
         CALL MPI_BCAST(Ham_U    ,  1,MPI_REAL8    ,0,Group_Comm,ierr)
         CALL MPI_BCAST(Dtau     ,  1,MPI_REAL8    ,0,Group_Comm,ierr)
         CALL MPI_BCAST(Beta     ,  1,MPI_REAL8    ,0,Group_Comm,ierr)
         CALL MPI_BCAST(Projector,  1,MPI_LOGICAL  ,0,Group_Comm,ierr)
         CALL MPI_BCAST(Theta    ,  1,MPI_REAL8    ,0,Group_Comm,ierr)
         CALL MPI_BCAST(Symm     ,  1,MPI_LOGICAL  ,0,Group_Comm,ierr)
         CALL MPI_BCAST(N_part   ,  1,MPI_INTEGER  ,0,Group_Comm,ierr)
#endif

      end subroutine read_parameters


#ifdef HDF5
      Subroutine write_parameters_hdf5(filename)
         Use hdf5
         use alf_hdf5
         Implicit none

         Character (len=64), intent(in) :: filename

         Logical            :: link_exists
         INTEGER(HID_T)     :: file_id, group_id, group_id2
         INTEGER            :: ierr

         ! Open HDF5 file
         CALL h5fopen_f (filename, H5F_ACC_RDWR_F, file_id, ierr)

         CALL h5lexists_f(file_id, "parameters", link_exists, ierr)
         if ( .not. link_exists ) then
           ! Create parameters-group
           call h5gcreate_f(file_id, "parameters", group_id, ierr)
         else
           ! Open parameters-group
           call h5gopen_f (file_id, "parameters", group_id, ierr)
         endif

CALL h5lexists_f(group_id, "var_lattice", link_exists, ierr)
                       if ( .not. link_exists ) then
                         call h5gcreate_f(group_id, "var_lattice", group_id2, ierr)
                         call h5gclose_f(group_id2, ierr)
                       endif
         call test_attribute(group_id, "var_lattice", "model", Model, ierr)
         call test_attribute(group_id, "var_lattice", "lattice_type", Lattice_type, ierr)
         call test_attribute(group_id, "var_lattice", "l1", L1, ierr)
         call test_attribute(group_id, "var_lattice", "l2", L2, ierr)
CALL h5lexists_f(group_id, "var_hubbard_plain_vanilla", link_exists, ierr)
                       if ( .not. link_exists ) then
                         call h5gcreate_f(group_id, "var_hubbard_plain_vanilla", group_id2, ierr)
                         call h5gclose_f(group_id2, ierr)
                       endif
         call test_attribute(group_id, "var_hubbard_plain_vanilla", "ham_t", ham_T, ierr)
         call test_attribute(group_id, "var_hubbard_plain_vanilla", "ham_ty", ham_Ty, ierr)
         call test_attribute(group_id, "var_hubbard_plain_vanilla", "ham_chem", Ham_chem, ierr)
         call test_attribute(group_id, "var_hubbard_plain_vanilla", "ham_u", Ham_U, ierr)
         call test_attribute(group_id, "var_hubbard_plain_vanilla", "dtau", Dtau, ierr)
         call test_attribute(group_id, "var_hubbard_plain_vanilla", "beta", Beta, ierr)
         call test_attribute(group_id, "var_hubbard_plain_vanilla", "projector", Projector, ierr)
         call test_attribute(group_id, "var_hubbard_plain_vanilla", "theta", Theta, ierr)
         call test_attribute(group_id, "var_hubbard_plain_vanilla", "symm", Symm, ierr)
         call test_attribute(group_id, "var_hubbard_plain_vanilla", "n_part", N_part, ierr)

         call h5gclose_f(group_id, ierr)
         call h5fclose_f(file_id, ierr)

      end Subroutine write_parameters_hdf5
#endif
